sudo: required

services:
  - docker

script:
  - docker build -t criteo/mesos-command-modules .
  - docker run -v $(pwd):/src/mesos-command-modules criteo/mesos-command-modules /bin/bash -c 'cd mesos-command-modules && mkdir build && cd build && cmake .. && make && make check'
